name: ✨ 功能请求
description: 建议为Lamina添加新功能
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您为Lamina提出新功能建议！请填写以下信息帮助我们理解您的需求。

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      description: 在提交功能请求前，请确认以下事项
      options:
        - label: 我已经搜索了现有的issues，确认这不是重复请求
          required: true
        - label: 我已经查看了项目的路线图和文档
          required: true
        - label: 这个功能与Lamina的设计目标一致（专注于精确数学计算）
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型
      description: 请选择最符合您需求的功能类型
      options:
        - 语言特性 (新的语法、操作符等)
        - 数学功能 (新的数学运算、函数等)
        - 标准库扩展 (新的内置函数、模块等)
        - 工具改进 (编译器、解释器改进等)
        - 性能优化
        - 开发体验改进
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 问题描述
      description: 请描述您当前遇到的问题或限制
      placeholder: |
        现在我在使用Lamina时遇到了什么困难？
        为什么现有的功能无法满足需求？
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 建议的解决方案
      description: 请详细描述您希望添加的功能
      placeholder: |
        请详细描述您期望的功能：
        - 新功能应该如何工作？
        - 用户如何使用这个功能？
        - 需要什么新的语法或API？
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: 使用示例
      description: 请提供展示新功能如何使用的代码示例
      render: lamina
      placeholder: |
        // 展示新功能的使用方式
        func example() {
            // 期望的代码写法
            new_feature_usage();
        }

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 请描述您考虑过的其他解决方案
      placeholder: |
        - 方案A: ...
        - 方案B: ...
        - 为什么选择建议的方案？

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能的优先级如何？
      options:
        - 低 (可有可无的改进)
        - 中 (会显著改善使用体验)
        - 高 (严重影响了我使用Lamina)
        - 紧急 (阻塞了重要工作)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 使用场景
      description: 请描述这个功能的具体使用场景
      placeholder: |
        - 场景1: 在科学计算中...
        - 场景2: 在教育应用中...
        - 场景3: 在数据分析中...

  - type: textarea
    id: compatibility
    attributes:
      label: 兼容性考虑
      description: 这个功能是否会影响现有代码的兼容性？
      placeholder: |
        - 是否是破坏性变更？
        - 是否需要语法变更？
        - 对性能的影响？

  - type: checkboxes
    id: implementation
    attributes:
      label: 实现意愿
      description: 您是否愿意参与这个功能的实现？
      options:
        - label: 我愿意提交PR来实现这个功能
        - label: 我可以协助设计API接口
        - label: 我可以提供测试用例
        - label: 我可以帮助编写文档

  - type: textarea
    id: additional-context
    attributes:
      label: 额外信息
      description: 添加任何其他有助于理解这个功能请求的信息
      placeholder: |
        - 相关的学术论文或技术资料
        - 其他语言中的类似实现
        - 截图或图表
        - 任何其他相关信息
