name: ❓ 问题求助
description: 在使用Lamina时遇到的问题或需要帮助
title: "[Help] "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        需要帮助？我们很乐意协助您！请详细描述您的问题，这样我们可以更好地帮助您。

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      options:
        - label: 我已经搜索了现有的issues和Wiki
          required: true
        - label: 我已经查看了相关文档
          required: true
        - label: 这不是一个bug报告（如果是bug，请使用bug报告模板）
          required: true

  - type: dropdown
    id: help-category
    attributes:
      label: 问题类别
      description: 请选择最符合您问题的类别
      options:
        - 安装和编译
        - 语法使用
        - 数学运算
        - 插件开发
        - 性能问题
        - 最佳实践
        - 代码示例请求
        - 其他
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 环境信息
      description: 您的操作系统和Lamina版本
      placeholder: "例如: Windows 11, Lamina v1.0.0"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 问题描述
      description: 请详细描述您的问题或需求
      placeholder: |
        - 您想要实现什么？
        - 遇到了什么困难？
        - 期望的结果是什么？
    validations:
      required: true

  - type: textarea
    id: current-code
    attributes:
      label: 当前代码
      description: 请提供您当前的代码（如果适用）
      render: lamina
      placeholder: |
        // 您当前的Lamina代码

  - type: textarea
    id: attempted-solutions
    attributes:
      label: 尝试过的解决方案
      description: 请描述您已经尝试过的方法
      placeholder: |
        我已经尝试了：
        1. ...
        2. ...

  - type: textarea
    id: additional-context
    attributes:
      label: 额外信息
      description: 提供任何其他可能有用的信息
      placeholder: |
        - 错误消息
        - 相关链接
        - 截图等
