name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR Description
      uses: actions/github-script@v6
      with:
        script: |
          const pr = context.payload.pull_request;
          const body = pr.body || '';
          
          // 检查PR描述是否包含基本信息
          const requiredSections = [
            '变更描述',
            '测试',
            '检查清单'
          ];
          
          const missingSections = requiredSections.filter(section => 
            !body.includes(section)
          );
          
          if (missingSections.length > 0) {
            core.setFailed(`PR描述缺少以下必要部分: ${missingSections.join(', ')}`);
          }
          
          // 检查是否填写了变更类型
          const hasChangeType = /- \[x\]/.test(body);
          if (!hasChangeType) {
            core.warning('请在PR描述中选择至少一种变更类型');
          }
          
          // 检查是否有相关的issue链接（可选）
          const hasIssueLink = /Closes #\d+|Related to #\d+/.test(body);
          if (!hasIssueLink) {
            core.info('建议在PR中关联相关的issue');
          }
          
          console.log('PR描述验证完成');

    - name: Check for Breaking Changes
      uses: actions/github-script@v6
      with:
        script: |
          const pr = context.payload.pull_request;
          const body = pr.body || '';
          const title = pr.title || '';
          
          // 检查是否有破坏性变更
          const hasBreakingChange = 
            title.includes('BREAKING') || 
            body.includes('破坏性变更') ||
            body.includes('breaking change');
          
          if (hasBreakingChange) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['breaking-change']
            });
            
            core.warning('⚠️ 此PR包含破坏性变更，请确保：\n1. 在描述中详细说明变更内容\n2. 更新相关文档\n3. 考虑版本号变更');
          }

    - name: Welcome First Time Contributors
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
          🎉 感谢您的第一次贡献！
          
          欢迎加入Lamina社区！我们很高兴看到您的贡献。
          
          在您的PR被review期间，请确保：
          - ✅ 代码符合项目规范
          - ✅ 包含必要的测试
          - ✅ 更新了相关文档
          
          如果您有任何问题，可以：
          - 💬 加入我们的QQ群：https://qm.qq.com/q/QwPXCgsJea
          - 📖 查看贡献指南：https://github.com/lamina-dev/Lamina/blob/main/documents/CONTRIBUTING-CN.md
          
          再次感谢您的贡献！🚀
